# k-近邻算法 无归一化

飞机里程数 对于结果的影响 远大于 其他两个，原因 仅仅是 里程数 远大于 其他两个。

但，这三个特征值 是 同等重要的

归一化，将取值范围 处理为0到1之间， 或者 -1到1之间

In [2]:
from collections import Counter
import operator

def k_Nearest_Neighbor(group,labels,new,k):
    all_error = []
    for i,j in zip(group,labels):
        sum_sq = sum([(i[k]-new[k])**2 for k in range(len(i))])
        error = sum_sq**0.5
        all_error.append([error,j])
    #print("all_error\n",all_error)
    all_error.sort()
    #print("sorted all_error\n",all_error)
    #print("all_error[:k]\n",all_error[:k])
    
    first_k_labels = [i[1] for i in all_error[:k]]
    print("first_k_labels\n",first_k_labels)
        
    label_counter = Counter(first_k_labels)
    
    #label_counter = {"a":2,"b":4,"c":1,"d":4}
    print("label_counter\n",label_counter)
    max_value = max(label_counter.items(), key=operator.itemgetter(1))[1]
    print("max_value",max_value)
    max_labels = []
    for key,value in label_counter.items():
        if value == max_value:
            max_labels.append(key)
 
    print("max_labels\n",max_labels)
    return max_labels

In [8]:
# Input
import numpy as np
group = []
labels = []
with open("datingTestSet2.txt") as f:
    for i in f:
        instance = i.split()
        for i in range(3):
            instance[i] = float(instance[i])
        group.append(instance[:3])
        labels.append(instance[3])
group = np.array(group)
labels = np.array(labels)
print(group[:5])
print(labels[:5])

[[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 [7.5136000e+04 1.3147394e+01 4.2896400e-01]
 [3.8344000e+04 1.6697880e+00 1.3429600e-01]]
['3' '2' '1' '1' '1']


In [18]:
# 错误过程
# 应直接使用 矩阵变换，而不是 遍历
def normalize(group):
    for i in range(len(group[0])):
        maxVal = group[:,i].max()
        minVal = group[:,i].min()
        print(maxVal,minVal)
normalize(group)

91273.0 0.0
20.919349 0.0
1.695517 0.001156
